# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignIn_Up' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignIn_Up
  # Pods for onban

  # RxSwift
  pod 'RxSwift'
  pod 'RxRelay'

  # Kakao
  pod 'KakaoSDKCommon' , '~> 2.11.1'
  pod 'KakaoSDKAuth'  , '~> 2.11.1'
  pod 'KakaoSDKUser' , '~> 2.11.1'

end
